# dataloader arguments
batch_size: 128
num_workers: 10
persistent_workers: true
pin_memory: true

# dataset
dataset_name: Surreal_Human_Segmentation
with_bb_cropping: True
with_rgb_masking: True
interp_size: [300, 200]

# optimizer
optimizer_type: sgd
base_lr: 0.01
weight_decay: 0.00005


# learning rate scheduler
lrs_scheduler: cosine_annealing
min_learning_rate: 0.0

# loss function
loss_fn: cross_entropy
ignore_index: 0

# training info
with_ddp: true
num_epochs: 10
with_validation: true
with_train_accuracy: false
starting_val_epoch: 1
with_16_bit_precision: true

# testing info
with_test: true
test_background: false
