# dataloader arguments
batch_size: 128
num_workers: 16
persistent_workers: true
pin_memory: true

# dataset
dataset_name: Surreal_Human_Segmentation
with_cropping: True
cropping_type: bb
interp_size: [240, 320]

# optimizer
optimizer_type: sgd
base_lr: 0.001
weight_decay: 0.00005
nesterov: true
momentum: 0.90

# learning rate scheduler
lrs_scheduler: cosine_annealing
min_learning_rate: 0.0

# loss function
loss_fn: sampled_cross_entropy

# training info
with_ddp: true
num_epochs: 30
with_validation: true
with_train_accuracy: false
starting_val_epoch: 1
with_16_bit_precision: true

# testing info
with_test: true
test_background: true
